
import React, {useMemo, useState} from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { Package, ShoppingCart, Users, BarChart3, AlertTriangle, Plus, Trash2, Pencil, Save, RotateCcw } from 'lucide-react';

const money = v => (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const today = () => new Date().toISOString().slice(0,10);
const uid = () => Math.random().toString(36).slice(2)+Date.now().toString(36);
const daysUntil = d => Math.ceil((new Date(d+'T00:00:00') - new Date(today()+'T00:00:00'))/86400000);

const seed = {
 products: [
  {id:'p1', nome:'Cera Premium', marca:'AutoShine', categoria:'Ceras', custo:28, venda:49.9, minimo:5},
  {id:'p2', nome:'Shampoo Alta Performance', marca:'LazerCar', categoria:'Shampoos', custo:18, venda:34.9, minimo:8},
  {id:'p3', nome:'Polidor Corte Rápido', marca:'BrilhoMax', categoria:'Polidores', custo:35, venda:69.9, minimo:4},
  {id:'p4', nome:'Pano Microfibra', marca:'SoftClean', categoria:'Acessórios', custo:4, venda:12, minimo:10}
 ],
 lots: [
  {id:'l1', productId:'p1', numero:'C-001', qtd:9, validade:'2026-06-20'},
  {id:'l2', productId:'p2', numero:'S-101', qtd:7, validade:'2026-07-15'},
  {id:'l3', productId:'p3', numero:'P-044', qtd:3, validade:'2026-08-05'},
  {id:'l4', productId:'p4', numero:'M-200', qtd:24, validade:'2027-01-10'}
 ],
 clients: [{id:'c1', nome:'João Silva', whatsapp:'21999990000'}],
 sales: []
};
function load(){ try { return JSON.parse(localStorage.getItem('autoLazerData')) || seed } catch { return seed } }
function save(d){ localStorage.setItem('autoLazerData', JSON.stringify(d)); }

export default function App(){
 const [data,setData] = useState(load()); const [tab,setTab]=useState('dashboard');
 const set = updater => setData(old => { const next = typeof updater==='function'?updater(old):updater; save(next); return next; });
 const estoquePorProduto = id => data.lots.filter(l=>l.productId===id).reduce((s,l)=>s+Number(l.qtd),0);
 const alertas = useMemo(()=>{
  const a=[]; data.products.forEach(p=>{ const qtd=estoquePorProduto(p.id); if(qtd<=Number(p.minimo)) a.push({tipo:'Estoque mínimo', texto:`${p.nome}: ${qtd} un. em estoque, mínimo ${p.minimo}`}); });
  data.lots.forEach(l=>{ const p=data.products.find(p=>p.id===l.productId); const d=daysUntil(l.validade); if(d>=0 && d<=30 && Number(l.qtd)>0) a.push({tipo:'Validade', texto:`${p?.nome||'Produto'} lote ${l.numero} vence em ${d} dia(s)`}); });
  return a;
 },[data]);
 const tabs=[['dashboard','Painel',BarChart3],['produtos','Produtos',Package],['lotes','Lotes',AlertTriangle],['pdv','PDV',ShoppingCart],['clientes','Clientes',Users],['relatorios','Relatórios',BarChart3]];
 return <div className="app"><aside><h1>Auto e Lazer</h1><p>Gestão de micro comércio</p>{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{label}</button>)}<button className="ghost" onClick={()=>{save(seed);setData(seed)}}><RotateCcw size={16}/>Restaurar demo</button></aside><main><header><h2>{tabs.find(t=>t[0]===tab)?.[1]}</h2><span>{new Date().toLocaleString('pt-BR')}</span></header>{tab==='dashboard'&&<Dashboard data={data} alertas={alertas} estoquePorProduto={estoquePorProduto}/>} {tab==='produtos'&&<Produtos data={data} set={set} estoquePorProduto={estoquePorProduto}/>} {tab==='lotes'&&<Lotes data={data} set={set}/>} {tab==='pdv'&&<PDV data={data} set={set}/>} {tab==='clientes'&&<Clientes data={data} set={set}/>} {tab==='relatorios'&&<Relatorios data={data}/>}</main></div>
}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Dashboard({data,alertas,estoquePorProduto}){
 const vendasHoje=data.sales.filter(s=>s.data.slice(0,10)===today()); const total=vendasHoje.reduce((s,v)=>s+v.total,0); const lucro=vendasHoje.reduce((s,v)=>s+v.lucro,0);
 const chart=data.products.map(p=>({nome:p.nome.split(' ')[0], estoque:estoquePorProduto(p.id)}));
 return <><div className="grid4"><Card><b>Produtos</b><h3>{data.products.length}</h3></Card><Card><b>Vendas hoje</b><h3>{vendasHoje.length}</h3></Card><Card><b>Faturamento hoje</b><h3>{money(total)}</h3></Card><Card><b>Lucro bruto hoje</b><h3>{money(lucro)}</h3></Card></div><div className="grid2"><Card><h3>Alertas automáticos</h3>{alertas.length?alertas.map((a,i)=><div className="alert" key={i}><strong>{a.tipo}</strong><span>{a.texto}</span></div>):<p>Nenhum alerta no momento.</p>}</Card><Card><h3>Estoque por produto</h3><ResponsiveContainer width="100%" height={260}><BarChart data={chart}><XAxis dataKey="nome"/><YAxis/><Tooltip/><Bar dataKey="estoque" /></BarChart></ResponsiveContainer></Card></div></>
}
function Produtos({data,set,estoquePorProduto}){ const blank={nome:'',marca:'',categoria:'',custo:'',venda:'',minimo:''}; const [f,setF]=useState(blank); const [edit,setEdit]=useState(null); const submit=()=>{ if(!f.nome) return; set(d=>({...d, products: edit? d.products.map(p=>p.id===edit?{...f,id:edit,custo:+f.custo,venda:+f.venda,minimo:+f.minimo}:p):[...d.products,{...f,id:uid(),custo:+f.custo,venda:+f.venda,minimo:+f.minimo}]})); setF(blank); setEdit(null)}; return <><Card><h3>{edit?'Editar':'Cadastrar'} produto</h3><div className="form">{['nome','marca','categoria','custo','venda','minimo'].map(k=><input key={k} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<button onClick={submit}><Save size={16}/>Salvar</button></div></Card><Card><table><thead><tr><th>Nome</th><th>Marca</th><th>Categoria</th><th>Custo</th><th>Venda</th><th>Estoque</th><th></th></tr></thead><tbody>{data.products.map(p=><tr key={p.id}><td>{p.nome}</td><td>{p.marca}</td><td>{p.categoria}</td><td>{money(p.custo)}</td><td>{money(p.venda)}</td><td>{estoquePorProduto(p.id)}</td><td><button className="mini" onClick={()=>{setF(p);setEdit(p.id)}}><Pencil size={14}/></button><button className="mini danger" onClick={()=>set(d=>({...d,products:d.products.filter(x=>x.id!==p.id), lots:d.lots.filter(l=>l.productId!==p.id)}))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></Card></>}
function Lotes({data,set}){ const [f,setF]=useState({productId:'',numero:'',qtd:'',validade:''}); const add=()=>{ if(!f.productId||!f.numero) return; set(d=>({...d,lots:[...d.lots,{...f,id:uid(),qtd:+f.qtd}]})); setF({productId:'',numero:'',qtd:'',validade:''}); }; return <><Card><h3>Novo lote</h3><div className="form"><select value={f.productId} onChange={e=>setF({...f,productId:e.target.value})}><option value="">Produto</option>{data.products.map(p=><option value={p.id} key={p.id}>{p.nome}</option>)}</select><input placeholder="Número do lote" value={f.numero} onChange={e=>setF({...f,numero:e.target.value})}/><input type="number" placeholder="Quantidade" value={f.qtd} onChange={e=>setF({...f,qtd:e.target.value})}/><input type="date" value={f.validade} onChange={e=>setF({...f,validade:e.target.value})}/><button onClick={add}><Plus size={16}/>Adicionar</button></div></Card><Card><table><thead><tr><th>Produto</th><th>Lote</th><th>Qtd</th><th>Validade</th><th>Status</th><th></th></tr></thead><tbody>{data.lots.map(l=>{const p=data.products.find(p=>p.id===l.productId); const d=daysUntil(l.validade); return <tr key={l.id}><td>{p?.nome}</td><td>{l.numero}</td><td>{l.qtd}</td><td>{l.validade}</td><td>{d<=30?'Atenção':'OK'}</td><td><button className="mini danger" onClick={()=>set(d=>({...d,lots:d.lots.filter(x=>x.id!==l.id)}))}><Trash2 size={14}/></button></td></tr>})}</tbody></table></Card></>}
function PDV({data,set}){ const [cart,setCart]=useState([]); const [pay,setPay]=useState('Dinheiro'); const [client,setClient]=useState(''); const add=p=>setCart(c=>{const e=c.find(i=>i.id===p.id); return e?c.map(i=>i.id===p.id?{...i,qtd:i.qtd+1}:i):[...c,{...p,qtd:1}]}); const total=cart.reduce((s,i)=>s+i.venda*i.qtd,0); const finish=()=>{ if(!cart.length)return; let lots=[...data.lots]; let ok=true, lucro=0; for(const item of cart){ let need=item.qtd; const sorted=lots.filter(l=>l.productId===item.id&&l.qtd>0).sort((a,b)=>a.validade.localeCompare(b.validade)); for(const l of sorted){ const take=Math.min(l.qtd, need); l.qtd-=take; need-=take; lucro += (item.venda-item.custo)*take; if(!need) break; } if(need>0) ok=false; } if(!ok){alert('Estoque insuficiente para algum item. Ajuste a venda.'); return} const sale={id:uid(),data:new Date().toISOString(),itens:cart.map(i=>({id:i.id,nome:i.nome,qtd:i.qtd,venda:i.venda,custo:i.custo})),pagamento:pay,clienteId:client,total,lucro}; set(d=>({...d,lots,sales:[...d.sales,sale]})); setCart([]); setClient('');}; return <div className="grid2"><Card><h3>Produtos</h3><div className="products">{data.products.map(p=><button key={p.id} onClick={()=>add(p)}><b>{p.nome}</b><span>{money(p.venda)}</span></button>)}</div></Card><Card><h3>Carrinho</h3>{cart.map(i=><div className="line" key={i.id}><span>{i.qtd}x {i.nome}</span><b>{money(i.qtd*i.venda)}</b></div>)}<hr/><div className="line total"><span>Total</span><b>{money(total)}</b></div><select value={pay} onChange={e=>setPay(e.target.value)}><option>Dinheiro</option><option>PIX</option><option>Cartão</option><option>Faturado</option></select><select value={client} onChange={e=>setClient(e.target.value)}><option value="">Cliente opcional</option>{data.clients.map(c=><option value={c.id} key={c.id}>{c.nome} - {c.whatsapp}</option>)}</select><button className="finish" onClick={finish}>Finalizar venda e baixar estoque</button></Card></div>}
function Clientes({data,set}){ const [f,setF]=useState({nome:'',whatsapp:''}); const add=()=>{ if(!f.nome)return; set(d=>({...d,clients:[...d.clients,{...f,id:uid()}]})); setF({nome:'',whatsapp:''})}; return <><Card><h3>Novo cliente</h3><div className="form"><input placeholder="Nome" value={f.nome} onChange={e=>setF({...f,nome:e.target.value})}/><input placeholder="WhatsApp" value={f.whatsapp} onChange={e=>setF({...f,whatsapp:e.target.value})}/><button onClick={add}><Plus size={16}/>Cadastrar</button></div></Card><div className="grid2">{data.clients.map(c=><Card key={c.id}><h3>{c.nome}</h3><p>{c.whatsapp}</p><h4>Histórico</h4>{data.sales.filter(s=>s.clienteId===c.id).map(s=><div className="line" key={s.id}><span>{new Date(s.data).toLocaleDateString('pt-BR')} · {s.pagamento}</span><b>{money(s.total)}</b></div>)}</Card>)}</div></>}
function Relatorios({data}){ const [ini,setIni]=useState(today()); const [fim,setFim]=useState(today()); const vendas=data.sales.filter(s=>s.data.slice(0,10)>=ini&&s.data.slice(0,10)<=fim); const total=vendas.reduce((s,v)=>s+v.total,0), lucro=vendas.reduce((s,v)=>s+v.lucro,0); const porPag=['Dinheiro','PIX','Cartão','Faturado'].map(p=>({nome:p,valor:vendas.filter(v=>v.pagamento===p).reduce((s,v)=>s+v.total,0)})); const agrup={}; vendas.forEach(v=>v.itens.forEach(i=>{agrup[i.nome]=agrup[i.nome]||{nome:i.nome,qtd:0,faturamento:0}; agrup[i.nome].qtd+=i.qtd; agrup[i.nome].faturamento+=i.qtd*i.venda})); let acum=0; const abc=Object.values(agrup).sort((a,b)=>b.faturamento-a.faturamento).map(x=>{acum+=x.faturamento; const pct=total?acum/total*100:0; return {...x,classe:pct<=80?'A':pct<=95?'B':'C'}}); return <><Card><h3>Período</h3><div className="form"><input type="date" value={ini} onChange={e=>setIni(e.target.value)}/><input type="date" value={fim} onChange={e=>setFim(e.target.value)}/></div></Card><div className="grid2"><Card><h3>Fechamento de caixa</h3>{porPag.map(p=><div className="line" key={p.nome}><span>{p.nome}</span><b>{money(p.valor)}</b></div>)}<hr/><div className="line total"><span>Total</span><b>{money(total)}</b></div><div className="line total"><span>Lucro bruto</span><b>{money(lucro)}</b></div></Card><Card><h3>Pagamento</h3><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={porPag} dataKey="valor" nameKey="nome" outerRadius={90} label>{porPag.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip formatter={money}/></PieChart></ResponsiveContainer></Card></div><Card><h3>Curva ABC</h3><table><thead><tr><th>Produto</th><th>Qtd</th><th>Faturamento</th><th>Classe</th></tr></thead><tbody>{abc.map(a=><tr key={a.nome}><td>{a.nome}</td><td>{a.qtd}</td><td>{money(a.faturamento)}</td><td><b>{a.classe}</b></td></tr>)}</tbody></table></Card></>}
