spring.application.name=ap10

# URL de conexão (cria o arquivo faeterj_repositorio.db na raiz do projeto)
spring.datasource.url=jdbc:sqlite:faeterj_repositorio.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuração do Dialeto para o SQLite
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect

# Atualiza a estrutura do banco automaticamente quando você cria ou altera as entidades (Models)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true